# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef72ac5314f8c6272d2de0f9acd2a47b"
name = "Blujay Logistics Client"
application_url = "https://blujaylogistic.com"
embedded = false

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify/gdpr/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify/gdpr/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify/gdpr/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_fulfillments"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://blujaylogistic.com/api/integrations/shopify/callback"
]

[pos]
embedded = false
