# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ae14d07c4c5cd48c68f9a5cb637901c"
name = "Blujay Logistics Client 3R1"
application_url = "https://blujaylogistic.com"
embedded = false

[build]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify3/gdpr/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify3/gdpr/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify3/gdpr/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
scopes = "read_orders,write_fulfillments"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://blujaylogistic.com/api/integrations/shopify3/callback"
]

[pos]
embedded = false
