# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1bea4752239e2570f3fec72f1a53547"
name = "Blujay Logistics Client 2"
application_url = "https://blujaylogistic.com"
embedded = false

[build]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify2/gdpr/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify2/gdpr/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/integrations/shopify2/gdpr/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://blujaylogistic.com/api/integrations/shopify2/callback"
]

[pos]
embedded = false
